"""empty message

Revision ID: 7d03e2bfa528
Revises: 6776140e1973
Create Date: 2023-10-21 20:59:06.527966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d03e2bfa528'
down_revision = '6776140e1973'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demo', schema=None) as batch_op:
        batch_op.drop_column('age')

    # ### end Alembic commands ###
